/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// eslint-disable-next-line @typescript-eslint/class-name-casing
export interface definitions {
  Article: {
    url?: string;
    created_at?: string;
    updated_at?: string;
    deleted_at: string;
    title: string;
    description: string;
  };
  Group: { url?: string; name: string };
  User: {
    url?: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    email?: string;
    /**
     * The groups this user belongs to. A user will get all permissions granted to each of their groups.
     */
    groups?: string[];
  };
}
